version: 1.0

mysql:
  mara:
    type:
    host: 127.0.0.1
    port: 3306
    user: root
    password: root
    destination: /backup/prepare/PROJECT1/databases/
    gzip: true
    blacklist: ["performance_schema",]
